# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxTodoExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   # Architecture
  pod 'ReactorKit'

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxOptional'
  pod 'RxViewController'

  # UI
  pod 'SnapKit'
  pod 'ManualLayout'

  # Misc.
  pod 'Then'
  pod 'ReusableKit'
  pod 'CGFloatLiteral'
  pod 'URLNavigator'



  # Pods for RxTodoExample

end
